### PR TITLE
Fixing a little mistake

### PR DESCRIPTION
**Pull request by albertmolodec**

### CODE REVIEW

**Comment by Norserium** [comment]
Thanks for your pull request and revealing that misspell.

But I suppose setting `overflow: scroll` is not a right solution, because [it will add](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) constant scrollbars at the right and bottom sides.

It's better to set `overflow: auto` as I desired before.
```js
style={{ ...style, overflow: hideScrollbars ? 'hidden' : 'auto' }}
```

**Comment by albertmolodec** [comment]
@Norserium 
Yeap.
Initially I wrote in my project `'auto'`, but when I did merge request, I accidentally wrote `scroll` 😅

I fixed it.

**Comment by albertmolodec** [comment]
P.S. Thanks for a good library. It helped me.

**Comment by Norserium** [comment]
Could you squash your commits into one _"fix the misspell in setting the overflow property of the container style"_?

It will require you to do force push (`git push --force`). It's commonly dangerous practice if your branch is used by multiple developers, but it shouldn't cause troubles if you are only one developer of a branch.

P.S. You are welcome!

**Comment by albertmolodec** [comment]
I did it once, then I thought I did it wrong, and pushed again 🤦‍♂️

**Comment by Norserium** [comment]
Thank you! But I forgotten, that I could do it myself by the github "squash and merge" tool.

**Comment by Norserium** [comment]
How did you do squash?

**Comment by albertmolodec** [comment]
I use GitKraken
image

git log:
```
commit fe2b2fb0402a03117cde18d3cea5b74d12450fb1 (HEAD -> master, origin/master,                                                                                                                                                                                                origin/HEAD)
Merge: b8e8e43 e99f069
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:59:45 2019 +0500

    Merge remote-tracking branch 'origin/master'

commit b8e8e43adcf347c2a0747e16c60ac1776eff09fc
Merge: 0dd0fdb f15da45
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:58:36 2019 +0500

    Fix the misspell in setting the overflow property of the container style

commit e99f069762c1b2a761f1be19ac7681f07109d419
Merge: 0dd0fdb f15da45
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:58:36 2019 +0500

    Merge remote-tracking branch 'origin/master'

commit 0dd0fdb3f118b871f1e7571c9a5496d0707540f5
:...skipping...
commit fe2b2fb0402a03117cde18d3cea5b74d12450fb1 (HEAD -> master, origin/master, origin/HEAD)
Merge: b8e8e43 e99f069
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:59:45 2019 +0500

    Merge remote-tracking branch 'origin/master'

commit b8e8e43adcf347c2a0747e16c60ac1776eff09fc
Merge: 0dd0fdb f15da45
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:58:36 2019 +0500

    Fix the misspell in setting the overflow property of the container style

commit e99f069762c1b2a761f1be19ac7681f07109d419
Merge: 0dd0fdb f15da45
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:58:36 2019 +0500

    Merge remote-tracking branch 'origin/master'

commit 0dd0fdb3f118b871f1e7571c9a5496d0707540f5
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:57:55 2019 +0500

    Fix the misspell in setting the overflow property of the container style

commit f15da45a3fa189c1e421e8fe573fde54a3b7c113
Author: Albert Abdulmanov <albert.abdu@gmail.com>
Date:   Fri Apr 26 14:40:18 2019 +0500

    fix of fix
```

**Comment by Norserium** [comment]
I've never used GitKraken, so it's pretty hard to comment what it did.

**Comment by albertmolodec** [comment]
I can fork your repo again and give my commit more understandable name.

So everything will definitely go well.

**Comment by Norserium** [comment]
No, it really doesn't matter. I want to show you how `rebase` can help you to make commits history beautiful and accurate.

**Comment by albertmolodec** [comment]
It will be great. Thanks.

**Comment by Norserium** [comment]
You can find the good review of rebase feature [here](https://ru.atlassian.com/git/tutorials/rewriting-history/git-rebase). But for start you can try to use rebase for changing history and squashing commits. The simplest instruction is [here](https://stackoverflow.com/a/5189600).

**Comment by Norserium** [comment]
I suppose you encountered some troubles during rebase right now, because of your non linear history (it looks like you merged the branch with itself).

So let's make your history linear and rebase your commits at the last my commit (115c3d8):
```
git rebase -i 115c3d8
```

Then you should see the following text in your default editor:
```
pick 0dd0fdb Fix the misspell in setting the overflow property of the container style
pick fa38cc8 fix a little mistake
pick f15da45 fix of fix
```

We choose to pick the latest commit and squash the others one:
```
pick 0dd0fdb Fix the misspell in setting the overflow property of the container style
squash fa38cc8 fix a little mistake
squash f15da45 fix of fix
```

You will get merge conflict in `src/index.js`. Fix it.

Then enter:
```
git add src/index.js
git rebase --continue
```

Your editor will open again and you should choice the right commit message of merged ones:
```
# This is a combination of 2 commits.
# This is the 1st commit message:

Fix the misspell in setting the overflow property of the container style

# This is the commit message #2:

fix of fix
```

Of course it's the first message, remove other one, save file and exit. Then just execute `git push --force`.

**Comment by albertmolodec** [comment]
Yes, I am faced with conflicts. Try to follow your instruction.

**Comment by albertmolodec** [comment]
Thanks, your advice helped me a lot!

**Comment by Norserium** [comment]
I suppose you can do rebase by GitKraken too, and it's pretty convenient to rebasing at, for example, JetBrains IDE.

Maybe the problem were in using `merge --squash` feature. It usually used to merge with some other branch.

**Comment by Norserium** [comment]
@albertmolodec, changes are published to `npm`.

**Comment by albertmolodec** [comment]
@Norserium 
Thank you :)

**Pull request merged**
