### PR TITLE
Add overrideRef prop for #51

### PR DESCRIPTION
**Pull request by n0099**
see #51

### CODE REVIEW

**Comment by Norserium** [comment]
I assume this code will work on desktop devices, but it won't on touch devices. At least, the events `onStartScroll`, `onEndScroll` and `onScroll` won't work correctly.

**Comment by n0099** [comment]
I've tested on multi mobile devices including android 11 (chrome 88.0.4324) and ios 14.4 (safari 604.1), they all working properly.

**Comment by Norserium** [comment]
Could you test `ScrollContainer` events `onStartScroll`,  `onScroll` and `onEndScroll`? They should be fired on start, scroll and end touch scroll.

**Comment by Norserium** [comment]
@n0099 could you test at mobile device [this code](https://codesandbox.io/s/example-of-problem-tvry9) locally with your changes? It should show alert "End Scroll" on the end of touch scrolling.

**Comment by n0099** [comment]
Same with you, all on(Start/End)Scroll event props don't get trigger when touching, tested on f12 mobile mode, android's chrome, and safari on ios.

**Comment by n0099** [comment]
I find that touch scroll events will go through to parent dom. In my local [demo](https://n0099.net/dev/test-react-indiana-drag-scroll), scrolling list at the right side will cause full-page to be scroll down, seems we have to set this.onScroll event handler on the overrideRef instead of <Component>.
https://github.com/Norserium/react-indiana-drag-scroll/blob/329221fc52a79b0af7dc9f3b6fb088535a206879/src/index.js#L126-L140

**Comment by Norserium** [comment]
Yes, but there is also some logic that hides scrollbars at mobile devices. It will be useless in this case and it may be pretty confusing.

**Comment by n0099** [comment]
> Yes, but there is also some logic that hides scrollbars at mobile devices. It will be useless in this case and it may be pretty confusing.

Isn't https://github.com/Norserium/react-indiana-drag-scroll/blob/329221fc52a79b0af7dc9f3b6fb088535a206879/src/style.css#L9-L21 this enough to hide scrollbar within element on all platform? Or you mean the body's scrollbar won't be invisible when it's scrolling due to touchmove events bubbling to the body in chrome mobile?

**Comment by Norserium** [comment]
@n0099, it's possible now in [the new major version](https://norserium.github.io/react-indiana-drag-scroll/docs/recipes#deep-ref).

**Pull request closed without merging**
